# -*- coding: utf-8 -*-
"""loss.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JuUQ43qZ1TVb4fJQLLipaC-YtXNtNhHV
"""

import numpy as np

################################################
#         Loss
################################################
class CrossEntropy():
	def __init__(self):
		pass

	def calc_loss(self, t, y):
		self.t = t
		self.y = y
		loss = -np.sum(np.sum(self.t*np.log(self.y)))
		return loss

	def diff(self):
		grad = -self.t/(self.y)
		return grad

class SquaredError():
	def __init__(self):
		pass

	def calc_loss(self, t, y):
		self.t = t
		self.y = y
		loss = np.sum((t-y)**2)
		return loss

	def diff(self, t_batch, y_batch):
		grad = -(t_batch - y_batch)
		return grad